server:
  port: 8089
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/vguserdb
    username: root
    password: Johns@2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8089/oauth2/jwks
      client:
        registration:
          github:
            clientId: ea0d55ec585ca6edb5c1
            clientSecret: aef512e6e1b9707fd3d372543a6f99d4fc5f881a
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.security: TRACE

keyFile: jwtused.jks
password: jwtused
alias: jwtused

providerUrl: http://localhost:8089

springdoc:
  api-docs:
    path: /userapi-doc
  swagger-ui:
    url: /userapi-spec.yaml
    path: /user-ui